CREATE DATABASE QUANLYKTX
USE QUANLYKTX
GO

CREATE TABLE TAIKHOAN
(
	ID INT PRIMARY KEY NOT NULL,
	TENDANGNHAP NVARCHAR(50),
	MATKHAU VARCHAR(50)
)



INSERT INTO TAIKHOAN VALUES
(1,'PhongDang','12345'),
(2,'DuyenTran','12345')

select * from TAIKHOAN

update TAIKHOAN set QUYEN = 'admin' where id = '12'